import React from 'react';
import farming from '../../assets/image/farming.png';
import Card from './Card';
const Farming = () => {
  return (
    <div className="container space-y-2 md:mt-[8rem] lg:px-12 py-6">
      <div
        id="farming"
        className="grid grid-cols-1 gap-y-10 px-8 lg:px-12  place-items-center py-3 md:grid-cols-2"
      >
        <div className="space-y-3 py-3 text-center md:text-left">
          <p className="text-[32px] font-sandro">Liquidity Yield Farming</p>
          <p className="text-[20px] font-MacPawFixel font-light leading-[1.5]">
            Join the revolution and take control of your financial future with
            Bubble's $BUB token.{' '}
          </p>
          <p className="text-[13px] text-[#C3C9DA]">
            With delegated community governance and stake-based earnings, you
            can now vote on proposals and earn passive income from the
            protocol's generated revenue. Empower yourself and become a part of
            the decentralized financial movement with Bubble.
          </p>
          <button className="btn-primary w-full md:w-auto px-4 py-3">
            Start Earning Yield
          </button>
        </div>
        <div className="flex items-center">
          <img className="w-[80%] block mx-auto" src={farming} alt="" />
        </div>
      </div>
      <div className="grid gap-1 grid-cols-1 md:grid-cols-2">
        <Card
          heading="Synthetic Yield Farming"
          title={
            'The BubbleSwap protocol enables users to maximize their profits by staking their liquidity provider (LP) tokens and earning synthetic yield rewards.'
          }
          subTitle="These rewards are determined by a liquidity provider tax, but are significantly increased when users lock their tokens for a specific duration. With this innovative form of yield farming, users can amplify their earnings while investing a smaller portion of their capital."
        />
        <Card
          heading="BUBBLE PROTOCOL FARMING"
          title="Join the innovative BubbleDeFi protocol and start earning real yield with your Bubble tokens"
          subTitle="Experience the unique 1:1 ratio of LP rewards and enjoy a sustainable form of APY that's based on actual revenue generated by the protocol. Say goodbye to fixed APY and the inflation it creates, and embrace the future of decentralized finance with Bubble."
        />
      </div>
    </div>
  );
};

export default Farming;
