import React from 'react';

import Card from './Card';

const Farming = () => {
  return (
    <div className="container px-0 space-y-2 md:mt-[8rem] lg:px-12 py-6">
      <div
        id="farming"
        className="grid  rounded-0 md:rounded-3xl grid-cols-1 gap-y-10  px-8 lg:px-12  py-3 md:grid-cols-2"
      >
        <div className="space-y-6 md:space-y-3 pt-7 py-3 text-center md:text-left">
          <p className="font-light text-[1em] md:text-[2em] uppercase font-sandro">
            Liquidity Yield Farming
          </p>
          <p className="text-[0.875em] md:text-[1.25em] font-MacPawFixel  leading-[1.5]">
            Join the revolution and take control of your financial future with
            Bubble's $BUB token.
          </p>
          <p className="text-[0.813em] text-[#C3C9DA]">
            With delegated community governance and stake-based earnings, you
            can now vote on proposals and earn passive income from the
            protocol's generated revenue. Empower yourself and become a part of
            the decentralized financial movement with Bubble.
          </p>
          <button
            title="comming soon..."
            className="btn-primary uppercase w-full md:w-auto px-4 py-4"
          >
            Start Earning Yield
          </button>
        </div>
        <div className="flex pt-5 items-center">
          <img
            className="w-full max-w-[400px] block my-4 mx-auto"
            src={'/image/farming.png'}
            alt="farming"
          />
        </div>
      </div>
      <div className="grid gap-1 grid-cols-1 md:grid-cols-2">
        <Card
          heading="Synthetic Yield Farming"
          title={
            'The BubbleSwap protocol enables users to maximize their profits by staking their liquidity provider (LP) tokens and earning synthetic yield rewards.'
          }
          subTitle="These rewards are determined by a liquidity provider tax, but are significantly increased when users lock their tokens for a specific duration. With this innovative form of yield farming, users can amplify their earnings while investing a smaller portion of their capital."
        />
        <Card
          heading="BUBBLE PROTOCOL FARMING"
          title="Join the innovative BubbleDeFi protocol and start earning real yield with your Bubble tokens"
          subTitle="Experience the unique 1:1 ratio of LP rewards and enjoy a sustainable form of APY that's based on actual revenue generated by the protocol. Say goodbye to fixed APY and the inflation it creates, and embrace the future of decentralized finance with Bubble."
        />
      </div>
    </div>
  );
};

export default Farming;
